[package]
name = "nrf52dk-rs"
version = "0.0.0"
authors = ["Niklas Adolfsson <niklasadolfsson1@gmail.com>"]
build = "build.rs"
license = "MIT"
description = ""

[build-dependencies]
gcc = "0.3.46"

[profile.dev]
panic = "abort"
lto = true
debug = true

[profile.release]
panic = "abort"
lto = true
