[package]
name = "nrf52dk-rs"
version = "0.0.0"
authors = ["Niklas Adolfsson <niklasadolfsson1@gmail.com>"]
license = "MIT"
description = ""

[profile.dev]
panic = "abort"
lto = true
debug = true

[profile.release]
panic = "abort"
lto = true
